files:
  - source: /udata_front/theme/gouvfr/translations/gouvfr.pot
    translation: >-
      /udata_front/theme/gouvfr/translations/%two_letters_code%/LC_MESSAGES/%file_name%.po
    - source: /udata_front/theme/govrs/translations/govrs.pot
    translation: >-
      /udata_front/theme/govrs/translations/%two_letters_code%/LC_MESSAGES/%file_name%.po
  - source: /theme/js/locales/en.json
    translation: /theme/js/locales/%two_letters_code%.json
      - source: /theme/js/locales/sr.json
    translation: /theme/js/locales/%two_letters_code%.json
